feat: implement ludwig nlu helper extension
Hexastack/hexabot-helper-ludwig pull request #1
Opened 2024-12-16 13:50 UTC by MohamedAliBouhaouala

2024-12-16 14:10 UTC, marrouchi requested changes

2024-12-16 14:10 UTC, marrouchi commented on i18n/en/label.json
> +    "token": "API Token",
We don't have any API token (currently) for Ludwig, right ? If that is the case then we can remove this setting.

2024-12-16 14:10 UTC, marrouchi commented on index.helper.ts
> +    );
We need to adapt the format for Ludwig

2024-12-16 14:10 UTC, marrouchi commented on index.helper.ts
> +    );
Throw new Error('Method not implemented yet!')

Same for evaluate()

2024-12-16 14:10 UTC, marrouchi commented on index.helper.ts
> +  async process_incoming_nlu_payload(
JS is in camelCase ;)

2024-12-16 14:10 UTC, marrouchi commented on index.helper.ts
> +        // });
```suggestion

```

2024-12-16 14:10 UTC, marrouchi commented on index.helper.ts
> +        'Core NLU Helper : Unable to parse nlp result to extract best guess!',
```suggestion
        'Ludwig NLU Helper : Unable to parse nlp result to extract best guess!',
```

2024-12-16 14:10 UTC, marrouchi commented on package.json
> +    "name": "hexabot-helper-ludwig-nlu",
```suggestion
    "name": "hexabot-helper-ludwig",
```

2024-12-16 14:10 UTC, marrouchi commented on types.ts
> +export namespace RasaNlu {
Please update typing accordingly.

2024-12-16 14:28 UTC, MohamedAliBouhaouala commented on i18n/en/label.json
> +    "token": "API Token",
It's just a token for the Hexabot API to interact with the Ludwig NLU engine

2024-12-18 13:31 UTC, marrouchi requested changes

2024-12-18 13:31 UTC, marrouchi commented on index.helper.ts
> +        );
```suggestion
        const traitEntities = s.entities.find(
          (e) => entityMap[e.entity].lookups.includes('trait'),
        );
```

2024-12-18 13:31 UTC, marrouchi commented on index.helper.ts
> +    };
.We need to parse the results depending on the trait entities we have (we may not only have intent)

2024-12-18 17:26 UTC, marrouchi approved these changes

2024-12-18 17:26 UTC, merged